### ISSUE TITLE
When juror breaks multipleSeatsInRound assigments in detail view not updated correctly

### ISSUE THREAD

**Issue by yurloc** [yurloc/iypt-planner#33]
To reproduce:
  1. Load 2012 data, clear schedule.
  2. Set jury size to 8 in round 3.
  3. Solve and terminate as soon as schedule is initialized and multipleSeatsInRound is broken.
  4. Switch to round 3, alternate selection between the juror that sits in multiple juries and some other juror.

**Comment by yurloc** [comment]
Probably caused by this exception, which interrupts displaying details:
```
java.lang.IllegalArgumentException: Percentage must be a number between 0 and 1
	at org.apache.pivot.wtk.Meter.setPercentage(Meter.java:69)
	at org.iypt.planner.gui.JurorDetailsSkin.showJuror(JurorDetailsSkin.java:171)
	at org.iypt.planner.gui.JurorDetailsSkin.jurorChanged(JurorDetailsSkin.java:252)
	at org.iypt.planner.gui.JurorDetails$JurorDetailsListenerList.jurorChanged(JurorDetails.java:17)
	at org.iypt.planner.gui.JurorDetails.showJuror(JurorDetails.java:60)
	at org.iypt.planner.gui.PlannerWindow.showJurorDetails(PlannerWindow.java:451)
```
