### ISSUE TITLE
Cannot submit selected file in bias computation file browser

### ISSUE THREAD

**Issue by yurloc** [yurloc/iypt-planner#56]
![last_dir_bug_crop](https://cloud.githubusercontent.com/assets/673386/12433231/2a2a37d2-bf00-11e5-8221-d361575ec20e.png)

**Comment by yurloc** [comment]
This was caused by using `.` as the initial value of MRU (last used) directory and a faulty validation in the file browser sheet that checks selected file's parent == root directory of the sheet:
```
java.lang.IllegalArgumentException
	at org.apache.pivot.wtk.FileBrowser.setSelectedFiles(FileBrowser.java:290)
	at org.apache.pivot.wtk.skin.terra.TerraFileBrowserSkin$9.selectedRangesChanged(TerraFileBrowserSkin.java:835)
	at org.apache.pivot.wtk.TableView$TableViewSelectionListenerList.selectedRangesChanged(TableView.java:988)
	at org.apache.pivot.wtk.TableView.setSelectedRanges(TableView.java:1496)
	at org.apache.pivot.wtk.TableView.setSelectedRange(TableView.java:1434)
	at org.apache.pivot.wtk.TableView.setSelectedIndex(TableView.java:1419)
	at org.apache.pivot.wtk.skin.terra.TerraTableViewSkin.mouseDown(TerraTableViewSkin.java:1246)
	at org.apache.pivot.wtk.Component$ComponentMouseButtonListenerList.mouseDown(Component.java:481)
```
This piece of code probably is not ready to handle relative root directory (such as `.`):
```
289:            if (!file.getParentFile().equals(rootDirectory)) {
290:                throw new IllegalArgumentException();
291:            }
```
